"""add facebook_url and instagram_url columns to restaurants

Revision ID: 40aaea1e2f91
Revises: b2cc99eaea2d
Create Date: 2026-02-17 09:42:45.902435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40aaea1e2f91'
down_revision = 'b2cc99eaea2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('facebook_url', sa.String(length=500), nullable=True))
    op.add_column('restaurants', sa.Column('instagram_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'instagram_url')
    op.drop_column('restaurants', 'facebook_url')
    # ### end Alembic commands ###
